# Generated by Django 5.2.12 on 2026-04-04 06:05

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('excel_import', 'Excel Import')], default='manual', max_length=20)),
                ('contact_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_listings', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_listings',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='listings.businesslisting')),
            ],
            options={
                'db_table': 'email_verifications',
            },
        ),
        migrations.CreateModel(
            name='ListingCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_range', models.CharField(blank=True, max_length=50)),
                ('funding_stage', models.CharField(blank=True, max_length=50)),
                ('business_type_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial', to='listings.businesslisting')),
            ],
            options={
                'db_table': 'listing_commercial',
            },
        ),
        migrations.CreateModel(
            name='ListingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=30)),
                ('hq_country', models.CharField(blank=True, max_length=100)),
                ('hq_city', models.CharField(blank=True, max_length=100)),
                ('regions_served', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('timezone', models.CharField(blank=True, max_length=60)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='listings.businesslisting')),
            ],
            options={
                'db_table': 'listing_contact',
            },
        ),
        migrations.CreateModel(
            name='ListingIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('company_type', models.CharField(blank=True, choices=[('startup', 'Startup'), ('sme', 'SME'), ('enterprise', 'Enterprise'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20)),
                ('sector_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('headcount_range', models.CharField(blank=True, max_length=50)),
                ('website_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('other_social', models.JSONField(blank=True, default=dict)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='listings.businesslisting')),
            ],
            options={
                'db_table': 'listing_identity',
            },
        ),
        migrations.CreateModel(
            name='ListingKeyPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_people', to='listings.businesslisting')),
            ],
            options={
                'db_table': 'listing_key_people',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ListingOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_hq', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='listings.businesslisting')),
            ],
            options={
                'db_table': 'listing_offices',
            },
        ),
        migrations.CreateModel(
            name='ListingProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('category_tag', models.CharField(blank=True, max_length=100)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='listings.businesslisting')),
            ],
            options={
                'db_table': 'listing_products',
            },
        ),
    ]
