# Generated by Django 5.2.12 on 2026-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
